# -*- coding: utf-8 -*-
"""Copy of Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AitFVT-JGq6_i669IbjnYWvY6vGv7iac

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s.split()

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("The diameter of {planet} is {diameter} kilometers".format(planet = "Earth", diameter = 12742))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d.items())

print(d['k1'][3]['tricky'][3]['target'][3])

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

#4.1
import numpy as np
arr = np.zeros(10)
print(arr)

#4.1

arr = np.ones(10)*5
print(arr)

"""## 5. Create an array of all the even integers from 20 to 35"""

arr = np.arange(20,35,2)
print(arr)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

arr = np.arange(0,9).reshape(3,3)
print(arr)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
arr = np.concatenate((a, b))
print(arr)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

data = [1,2,3]
df = pd.DataFrame(data, columns=['Numbers'])
df

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

series = pd.date_range(start ='1-1-2023', end ='02-10-2023')
  
for val in series:
  print(val)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists)
df